server:
  port: 5555
spring:
  profiles:
    active: mysql
  mail:
    host: smtp.qq.com # 配置 SMTP 服务器地址
    username: 524519972@qq.com # 发送者邮箱
    password: cmcrvhaiqswabgji # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    port: 587 # 端口号465或587
    default-encoding: UTF-8 # 默认的邮件编码为UTF-8
    properties: # 配置SSL 加密工厂
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误

mybatis:
  config-location: classpath:config/mybatis-config.xml

logging:
  level:
    com.myyf.message: debug
    cn.jasonone.at: debug
    com.example: debug