spring:
  datasource:
    driver-class-name: org.h2.Driver
    # data: classpath:db/data.sql
    # schema: classpath:db/schema.sql
    url: jdbc:h2:file:./db/deployer.h2
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true